In [1]:
import numpy as np
import pandas as pd
from pylab import mpl, plt
import statsmodels.formula.api as smf
import statsmodels.api as sm
plt.style.use('seaborn')
mpl.rcParams['font.family'] = 'serif'
%matplotlib inline

In [9]:
conda install xlrd

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [27]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.9
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os 
os.getcwd()

'C:\\Users\\hy11\\pyproj'

In [22]:
data = pd.read_excel('Factset_corp.xls', header=0)  
data

,Identifier,Name,Revenue,Industry,Country,EV_EBITDA,PE,DY,ROE,D_EBITDA,SalesGrowth,EV_Sales,IntCoverage,Sales_Growth,NAICS
0,III-GB,3i Group plc,310.79575,Investment Managers,United Kingdom,5.714004,5.995946,3.337668,21.925419,0.475323,35.227272,50.105570,44.255318,-15.751022,Finance and Insurance
1,MMM-US,3M Company,35355.00000,Industrial Conglomerates,United States,12.364775,17.558964,3.332770,42.424675,1.849698,9.852722,3.325975,16.468271,2.568400,Manufacturing
2,MAERSK.B-DK,A.P. Moller - Maersk A/S,61802.00000,Marine Shipping,Denmark,3.183981,3.961301,10.660980,47.765522,0.667286,49.615580,1.230687,23.301353,16.147530,Transportation and Warehousing
3,SAGA.B-SE,AB Sagax,376.95100,Real Estate Development,Sweden,61.955906,13.799156,0.704918,36.640450,10.528740,9.806583,48.630410,5.680090,11.859679,Real Estate and Rental and Leasing
4,ABBN-CH,ABB Ltd.,28949.00000,Electrical Products,Switzerland,18.571790,16.953270,2.349570,30.139330,1.325531,8.146307,2.713895,22.216219,-0.825363,Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,ZM-US,"Zoom Video Communications, Inc.",4099.86400,Packaged Software,United States,34.879795,34.313420,0.000000,28.525830,0.000000,54.632020,10.209882,NaN,131.486270,Information
1596,ZI-US,"ZoomInfo Technologies, Inc.",747.20000,Internet Software/Services,United States,117.641014,216.526120,0.000000,9.341385,5.536146,56.908860,35.155594,3.494306,73.004280,Information
1597,ZS-US,"Zscaler, Inc.",673.10000,Packaged Software,United States,NaN,NaN,0.000000,-51.696320,NaN,56.074272,46.745193,-3.886440,52.396904,Information
1598,2057-HK,"ZTO Express (Cayman), Inc.",4714.55270,Air Freight/Couriers,China,20.291193,30.963827,0.000000,9.748559,0.540613,29.337803,4.579581,37.260040,20.677544,"Professional, Scientific, and Technical Services"
1599,ZURN-CH,Zurich Insurance Group AG,69591.00000,Multi-Line Insurance,Switzerland,NaN,12.517507,5.494505,13.916419,NaN,15.454802,1.227695,NaN,11.390471,Finance and Insurance

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Identifier    1600 non-null   object
 1   Name          1600 non-null   object
 2   Revenue       1600 non-null   float64
 3   Industry      1600 non-null   object
 4   Country       1600 non-null   object
 5   EV_EBITDA     1271 non-null   float64
 6   PE            1482 non-null   float64
 7   DY            1516 non-null   float64
 8   ROE           1559 non-null   float64
 9   D_EBITDA      1303 non-null   float64
 10  SalesGrowth   1594 non-null   float64
 11  EV_Sales      1539 non-null   float64
 12  IntCoverage   1328 non-null   float64
 13  Sales_Growth  1579 non-null   float64
 14  NAICS         1600 non-null   object
dtypes: float64(10), object(5)
memory usage: 187.6+ KB

In [34]:
data

,Identifier,Name,Revenue,Industry,Country,EV_EBITDA,PE,DY,ROE,D_EBITDA,SalesGrowth,EV_Sales,IntCoverage,Sales_Growth,NAICS
0,III-GB,3i Group plc,310.79575,Investment Managers,United Kingdom,5.714004,5.995946,3.337668,21.925419,0.475323,35.227272,50.105570,44.255318,-15.751022,Finance and Insurance
1,MMM-US,3M Company,35355.00000,Industrial Conglomerates,United States,12.364775,17.558964,3.332770,42.424675,1.849698,9.852722,3.325975,16.468271,2.568400,Manufacturing
2,MAERSK.B-DK,A.P. Moller - Maersk A/S,61802.00000,Marine Shipping,Denmark,3.183981,3.961301,10.660980,47.765522,0.667286,49.615580,1.230687,23.301353,16.147530,Transportation and Warehousing
3,SAGA.B-SE,AB Sagax,376.95100,Real Estate Development,Sweden,61.955906,13.799156,0.704918,36.640450,10.528740,9.806583,48.630410,5.680090,11.859679,Real Estate and Rental and Leasing
4,ABBN-CH,ABB Ltd.,28949.00000,Electrical Products,Switzerland,18.571790,16.953270,2.349570,30.139330,1.325531,8.146307,2.713895,22.216219,-0.825363,Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,ZM-US,"Zoom Video Communications, Inc.",4099.86400,Packaged Software,United States,34.879795,34.313420,0.000000,28.525830,0.000000,54.632020,10.209882,NaN,131.486270,Information
1596,ZI-US,"ZoomInfo Technologies, Inc.",747.20000,Internet Software/Services,United States,117.641014,216.526120,0.000000,9.341385,5.536146,56.908860,35.155594,3.494306,73.004280,Information
1597,ZS-US,"Zscaler, Inc.",673.10000,Packaged Software,United States,NaN,NaN,0.000000,-51.696320,NaN,56.074272,46.745193,-3.886440,52.396904,Information
1598,2057-HK,"ZTO Express (Cayman), Inc.",4714.55270,Air Freight/Couriers,China,20.291193,30.963827,0.000000,9.748559,0.540613,29.337803,4.579581,37.260040,20.677544,"Professional, Scientific, and Technical Services"
1599,ZURN-CH,Zurich Insurance Group AG,69591.00000,Multi-Line Insurance,Switzerland,NaN,12.517507,5.494505,13.916419,NaN,15.454802,1.227695,NaN,11.390471,Finance and Insurance

In [26]:
count_nan = data.isnull().sum()
print(count_nan)

Identifier        0
Name              0
Revenue           0
Industry          0
Country           0
EV_EBITDA       329
PE              118
DY               84
ROE              41
D_EBITDA        297
SalesGrowth       6
EV_Sales         61
IntCoverage     272
Sales_Growth     21
NAICS             0
dtype: int64

In [43]:
data = pd.read_excel('Factset_corp.xls', header=0)  

data2 = data.dropna()
data2

,Identifier,Name,Revenue,Industry,Country,EV_EBITDA,PE,DY,ROE,D_EBITDA,SalesGrowth,EV_Sales,IntCoverage,Sales_Growth,NAICS
0,III-GB,3i Group plc,310.79575,Investment Managers,United Kingdom,5.714004,5.995946,3.337668,21.925419,0.475323,35.227272,50.105570,44.255318,-15.751022,Finance and Insurance
1,MMM-US,3M Company,35355.00000,Industrial Conglomerates,United States,12.364775,17.558964,3.332770,42.424675,1.849698,9.852722,3.325975,16.468271,2.568400,Manufacturing
2,MAERSK.B-DK,A.P. Moller - Maersk A/S,61802.00000,Marine Shipping,Denmark,3.183981,3.961301,10.660980,47.765522,0.667286,49.615580,1.230687,23.301353,16.147530,Transportation and Warehousing
3,SAGA.B-SE,AB Sagax,376.95100,Real Estate Development,Sweden,61.955906,13.799156,0.704918,36.640450,10.528740,9.806583,48.630410,5.680090,11.859679,Real Estate and Rental and Leasing
4,ABBN-CH,ABB Ltd.,28949.00000,Electrical Products,Switzerland,18.571790,16.953270,2.349570,30.139330,1.325531,8.146307,2.713895,22.216219,-0.825363,Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,2899-HK,"Zijin Mining Group Co., Ltd.",34366.64500,Precious Metals,China,8.586947,12.881730,2.494376,25.025448,2.415552,40.661964,1.277647,9.105002,29.272438,"Mining, Quarrying, and Oil and Gas Extraction"
1593,ZBH-US,"Zimmer Biomet Holdings, Inc.",7836.20000,Medical Specialties,United States,14.704028,66.554900,0.755668,3.231556,3.118955,11.555273,4.289670,5.769973,-0.407988,Manufacturing
1594,ZTS-US,Zoetis Inc.,7776.00000,Pharmaceuticals: Major,United States,36.739850,57.109760,0.440520,49.013474,2.027684,16.494383,15.384934,10.949219,10.108316,Manufacturing
1596,ZI-US,"ZoomInfo Technologies, Inc.",747.20000,Internet Software/Services,United States,117.641014,216.526120,0.000000,9.341385,5.536146,56.908860,35.155594,3.494306,73.004280,Information
1598,2057-HK,"ZTO Express (Cayman), Inc.",4714.55270,Air Freight/Couriers,China,20.291193,30.963827,0.000000,9.748559,0.540613,29.337803,4.579581,37.260040,20.677544,"Professional, Scientific, and Technical Services"

In [44]:
data2.info()
data2.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1106 entries, 0 to 1598
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Identifier    1106 non-null   object
 1   Name          1106 non-null   object
 2   Revenue       1106 non-null   float64
 3   Industry      1106 non-null   object
 4   Country       1106 non-null   object
 5   EV_EBITDA     1106 non-null   float64
 6   PE            1106 non-null   float64
 7   DY            1106 non-null   float64
 8   ROE           1106 non-null   float64
 9   D_EBITDA      1106 non-null   float64
 10  SalesGrowth   1106 non-null   float64
 11  EV_Sales      1106 non-null   float64
 12  IntCoverage   1106 non-null   float64
 13  Sales_Growth  1106 non-null   float64
 14  NAICS         1106 non-null   object
dtypes: float64(10), object(5)
memory usage: 138.2+ KB

(1106, 15)

In [45]:
count_nan = data2.isnull().sum()
print(count_nan)

Identifier      0
Name            0
Revenue         0
Industry        0
Country         0
EV_EBITDA       0
PE              0
DY              0
ROE             0
D_EBITDA        0
SalesGrowth     0
EV_Sales        0
IntCoverage     0
Sales_Growth    0
NAICS           0
dtype: int64

In [46]:
formula = 'PE ~ EV_EBITDA + DY + ROE + D_EBITDA + SalesGrowth + EV_Sales + IntCoverage'
results = smf.ols(formula, data2).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     PE   R-squared:                       0.140
Model:                            OLS   Adj. R-squared:                  0.135
Method:                 Least Squares   F-statistic:                     25.62
Date:                Thu, 19 May 2022   Prob (F-statistic):           1.40e-32
Time:                        01:42:11   Log-Likelihood:                -6991.6
No. Observations:                1106   AIC:                         1.400e+04
Df Residuals:                    1098   BIC:                         1.404e+04
Df Model:                           7
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      17.3084      7.352      2.354      0.019       2.882      31.735
EV_EBITDA       2.2774      0.191     11.911      0.000       1.902       2.653
DY              1.4966      1.589      0.942      0.346      -1.621       4.614
ROE            -0.0073      0.015     -0.484      0.628      -0.037       0.022
D_EBITDA       -3.5978      0.575     -6.260      0.000      -4.726      -2.470
SalesGrowth    -0.0539      0.044     -1.223      0.222      -0.140       0.033
EV_Sales       -1.7671      0.729     -2.424      0.016      -3.197      -0.337
IntCoverage    -0.0075      0.011     -0.670      0.503      -0.029       0.014
==============================================================================
Omnibus:                     2200.055   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          4265277.384
Skew:                          15.095   Prob(JB):                         0.00
Kurtosis:                     305.728   Cond. No.                         679.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.