<a href="https://colab.research.google.com/github/cyrus723/my-first-binder/blob/main/wrds_compustat1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install wrds

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wrds in /usr/local/lib/python3.7/dist-packages (3.1.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from wrds) (1.21.6)
Requirement already satisfied: mock in /usr/local/lib/python3.7/dist-packages (from wrds) (4.0.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from wrds) (1.3.5)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.7/dist-packages (from wrds) (2.9.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from wrds) (1.4.37)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->wrds) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->wrds) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->wrds) (1.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->wrds) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->wrds) (4.11.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->wrds) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->wrds) (4.1.1)

In [2]:
import wrds

In [ ]:
# Now I am connecting to WRDS site - you must ahve a WRDS account user id and password
conn=wrds.Connection()

In [4]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [5]:
help(wrds)

Help on package wrds:

NAME
    wrds

DESCRIPTION
    WRDS Python Data Access Library
    ==============================

    WRDS-Py is a library for extracting data from WRDS data sources and getting it into Pandas.

        >>> import wrds
        >>> db = wrds.Connection()
        >>> db.list_libraries()
        ['aha', 'aha_sample', 'ahasamp', 'audit', 'audit_audit_comp', ...]
        >>> db.list_tables(library='crsp')
        ['acti', 'asia', 'asib', 'asic', 'asio', 'asix', 'bmdebt', 'bmheader', ...]
        >>> data = db.raw_sql('SELECT * FROM crsp.stocknames', index_col='permno')
        >>> data.head()
                 permco      namedt   nameenddt     cusip    ncusip ticker      permno
        10000.0  7952.0  1986-01-07  1987-06-11  68391610  68391610  OMFGA
        10001.0  7953.0  1986-01-09  1993-11-21  36720410  39040610   GFGC
        10001.0  7953.0  1993-11-22  2008-02-04  36720410  29274A10   EWST
        10001.0  7953.0  2008-02-05  2009-08-03  36720410  29274A20   EWST
        10001.0  7953.0  2009-08-04  2009-12-17  36720410  29269V10   EGAS
        ...

PACKAGE CONTENTS
    sql
    test

DATA
    __copyright__ = '2017-2021 Wharton Research Data Services'
    __title__ = 'wrds-py'

VERSION
    3.1.1

AUTHOR
    Wharton Research Data Services

FILE
    /usr/local/lib/python3.7/dist-packages/wrds/__init__.py

In [6]:
#listing all dtabases or libraries in WRDS
conn.list_libraries()

['compbd',
 'compgd',
 'compnad',
 'compsegd',
 'crspa',
 'evts',
 'issm',
 'nastraq',
 'tass',
 'wrds_lib_internal',
 'aha',
 'estimize',
 'levin',
 'ciqsamp_capstrct',
 'toyo',
 'ahasamp',
 'ciqsamp_pplintel',
 'crspm',
 'tresgsmp',
 'trsdcgs',
 'columnar',
 'trws',
 'lspd',
 'twoiq',
 'wcai',
 'tresg',
 'wind',
 'wqa',
 'msrb_all',
 'custom_jl',
 'risk',
 'centris',
 'wrdsapps_link_supplychain',
 'block_all',
 'zacks',
 'crsp',
 'contrib',
 'audit',
 'boardex_trial',
 'emdb',
 'calcbnch',
 'comp_na_monthly_all',
 'auditsmp',
 'boardsmp',
 'comp_segments_hist',
 'wrdsrpts_rep_usage',
 'public_all',
 'pwt_all',
 'msfanly',
 'etfg',
 'snlsamp_fig',
 'wrdsapps_backtest_plus',
 'pacap',
 'ciqsamp_transcripts',
 'ciq',
 'tr_ds',
 'ppublica',
 'crsp_a_stock',
 'preqin',
 'etfg_samp',
 'fisdsamp',
 'windsmp',
 'rent',
 'sustainalyticssamp_all',
 'wrdsapps_evtstudy_int_ginsight',
 'compmcur',
 'tr_dealscan',
 'markit',
 'secsamp_all',
 'rpna',
 'ibes',
 'rpa',
 'sdcsamp',
 'wrdssec_midas',
 'cisdmsmp',
 'cboe_all',
 'snl',
 'cboe',
 'sprat',
 'ciqsamp',
 'fjc_litigation',
 'trucost',
 'sustain',
 'trdssamp',
 'risksamp',
 'midas',
 'snlsamp',
 'public',
 'pwt',
 'repsamp',
 'snapsamp',
 'taqsamp',
 'totalq',
 'optionm',
 'comp_execucomp',
 'fjc_linking',
 'compa',
 'bank',
 'blab',
 'compb',
 'compg',
 'block',
 'taqmsec',
 'trsamp_ds_eq',
 'contrib_ceo_turnover',
 'cisdm',
 'clrvt',
 'clrvtsmp',
 'compm',
 'compseg',
 'compsamp',
 'comph',
 'compsnap',
 'comscore',
 'pitchbk',
 'crspsamp',
 'dmef',
 'eursamp',
 'contrib_kpss',
 'auditsmp_all',
 'crspq',
 'execcomp',
 'taqmsamp_all',
 'ff',
 'ftse',
 'cusipm',
 'boardex',
 'eureka',
 'eventus',
 'ftsesamp',
 'ginsight',
 'ktsamp',
 'factset',
 'ifgrsamp',
 'imssamp',
 'gmi',
 'fssamp',
 'govpxsmp',
 'hbsamp',
 'hbase',
 'hfr',
 'ibescorp',
 'mrktsamp_msf',
 'iri',
 'govpx',
 'kld',
 'ifgr',
 'ibeskpi',
 'fisd',
 'lspdsamp',
 'ims',
 'ktmine',
 'taq',
 'aha_sample',
 'compdcur',
 'calcbench_trial',
 'ciqsamp_common',
 'ppubsamp_d4d',
 'mrktsamp',
 'otc',
 'msrbsamp',
 'contrib_general',
 'preqsamp_all',
 'twoiq_samp',
 'msrb',
 'mrktsamp_cdx',
 'phlx_all',
 'zacksamp_all',
 'mfl',
 'sustsamp',
 'etfgsamp',
 'phlx',
 'ppubsamp',
 'preqsamp',
 'ciqsamp_keydev',
 'tfn',
 'toyosamp',
 'wappsamp',
 'wrdsapps_evtstudy_lr',
 'crsp_a_ccm',
 'zacksamp',
 'revere',
 'eurekahedge_sample',
 'comp_na_daily_all',
 'ims_obp_trial',
 'wrdsrpts',
 'compsamp_snapshot',
 'comp_na_annual_all',
 'rq_all',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'ktmine_patents_samp',
 'djones_all',
 'doe_all',
 'factsamp_all',
 'toyosamp_all',
 'wrdsapps_eushort',
 'wrdsapps_subsidiary',
 'wrdsappssamp_all',
 'wrdsapps_link_datastream_wscope',
 'wrdsapps_patents',
 'dmef_all',
 'macrofin_comm_trade',
 'mrktsamp_cds',
 'pitchsmp',
 'wrdsapps_link_comp_eushort',
 'totalq_all',
 'trsamp_dscom',
 'trsamp_dsecon',
 'wrdsapps_finratio',
 'reprisk',
 'comp',
 'trcstsmp',
 'rpnasamp',
 'audit_corp_legal',
 'csmar',
 'trsamp_dsfut',
 'wrdsapps_backtest_basic',
 'wrdsapps_link_crsp_bond',
 'ff_all',
 'wrdsapps_link_crsp_taq',
 'contrib_intangible_value',
 'wrdssec',
 'wrdsapps',
 'audit_common',
 'contrib_char_returns',
 'crsp_q_indexhist',
 'bvd',
 'secsamp',
 'factsamp_revere',
 'frb_all',
 'hbase_sample',
 'hfrsamp_hfrdb',
 'trown',
 'lvnsamp_all',
 'risksamp_all',
 'optionmsamp_europe',
 'optionmsamp_us',
 'reprisk_sample',
 'wrdsapps_finratio_ccm',
 'trace_standard',
 'trdstrm',
 'trace_enhanced',
 'fjc',
 'lvnsamp',
 'omtrial',
 'trace',
 'bvdsamp',
 'djones',
 'doe',
 'frb',
 'hfrsamp',
 'macrofin',
 'comp_bank',
 'trsamp',
 'wrdsapps_link_crsp_factset',
 'twoiqsmp',
 'comp_bank_daily',
 'audit_audit_comp',
 'comp_segments_hist_daily',
 'otc_endofday',
 'dealscan',
 'ravenpack_trial',
 'msfinst',
 'crsp_a_indexes',
 'taqmsamp',
 'iss',
 'sdc']

In [7]:
conn.list_tables(library='comp')

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'bank_aacctchg',
 'bank_adesind',
 'bank_afnd1',
 'bank_afnd2',
 'bank_afnddc1',
 'bank_afnddc2',
 'bank_afntind',
 'bank_funda',
 'bank_funda_fncd',
 'bank_fundq',
 'bank_fundq_fncd',
 'bank_iacctchg',
 'bank_idesind',
 'bank_ifndq',
 'bank_ifndytd',
 'bank_ifntq',
 'bank_ifntytd',
 'bank_names',
 'bank_namesq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'company',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'ecind_desc',
 'ecind_mth',
 'exrt_dly',
 'exrt_mth',
 'filings',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'g_chars',
 'g_co_aaudit',
 'g_co_adesind',
 'g_co_afnd1',
 'g_co_afnd2',
 'g_co_afnddc1',
 'g_co_afnddc2',
 'g_co_afntind1',
 'g_co_afntind2',
 'g_co_ainvval',
 'g_co_gsuppl',
 'g_co_hgic',
 'g_co_iaudit',
 'g_co_idesind',
 'g_co_ifndq',
 'g_co_ifndsa',
 'g_co_ifndytd',
 'g_co_ifntq',
 'g_co_ifntsa',
 'g_co_ifntytd',
 'g_co_industry',
 'g_co_ipcd',
 'g_co_offtitl',
 'g_company',
 'g_currency',
 'g_ecind_desc',
 'g_ecind_mth',
 'g_exrt_dly',
 'g_exrt_mth',
 'g_funda',
 'g_funda_fncd',
 'g_fundq',
 'g_fundq_fncd',
 'g_idx_daily',
 'g_idx_index',
 'g_idx_mth',
 'g_idxcst_his',
 'g_names',
 'g_names_ix',
 'g_names_ix_cst',
 'g_namesq',
 'g_sec_adesind',
 'g_sec_adjfact',
 'g_sec_afnd',
 'g_sec_afnddc',
 'g_sec_afnt',
 'g_sec_divid',
 'g_sec_dprc',
 'g_sec_dtrt',
 'g_sec_history',
 'g_sec_idesind',
 'g_sec_ifnd',
 'g_sec_ifnt',
 'g_sec_split',
 'g_secd',
 'g_secnamesd',
 'g_security',
 'g_sedolgvkey',
 'g_tmptable_pkg6153_tbl4023',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'tmptable_pkg6153_tbl4023',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

In [8]:
apple = conn.raw_sql("""select permno, date, prc, ret, shrout 
                        from crsp.msf 
                        where permno = 14593
                        and date>='01/01/2020'""", 
                     date_cols=['date'])
apple

     permno       date         prc       ret      shrout
0   14593.0 2020-01-31  309.510010  0.054010   4375480.0
1   14593.0 2020-02-28  273.359985 -0.114310   4375480.0
2   14593.0 2020-03-31  254.289993 -0.069761   4323987.0
3   14593.0 2020-04-30  293.799988  0.155374   4334335.0
4   14593.0 2020-05-29  317.940002  0.084956   4334335.0
5   14593.0 2020-06-30  364.799988  0.147386   4283939.0
6   14593.0 2020-07-31  425.040009  0.165132   4275634.0
7   14593.0 2020-08-31  129.039993  0.216309  17102536.0
8   14593.0 2020-09-30  115.809998 -0.102526  16976763.0
9   14593.0 2020-10-30  108.860001 -0.060012  17001802.0
10  14593.0 2020-11-30  119.050003  0.095490  17001802.0
11  14593.0 2020-12-31  132.690002  0.114574  16823263.0
12  14593.0 2021-01-29  131.960007 -0.005502  16788096.0
13  14593.0 2021-02-26  121.260002 -0.079532  16788096.0
14  14593.0 2021-03-31  122.150002  0.007340  16686305.0
15  14593.0 2021-04-30  131.460007  0.076218  16687631.0
16  14593.0 2021-05-28  124.610001 -0.050434  16687631.0
17  14593.0 2021-06-30  136.960007  0.099109  16556942.0
18  14593.0 2021-07-30  145.860001  0.064982  16530166.0
19  14593.0 2021-08-31  151.830002  0.042438  16530166.0
20  14593.0 2021-09-30  141.500000 -0.068037  16426786.0
21  14593.0 2021-10-29  149.800003  0.058657  16406397.0
22  14593.0 2021-11-30  165.300003  0.104940  16406397.0
23  14593.0 2021-12-31  177.570007  0.074229  16344923.0
24  14593.0 2022-01-31  174.779999 -0.015712  16319441.0
25  14593.0 2022-02-28  165.119995 -0.054011  16319441.0
26  14593.0 2022-03-31  174.610001  0.057473  16319441.0

In [10]:
company_narrow = conn.get_table(library='comp', table='company', 
                                columns = ['conm', 'gvkey', 'cik'], obs=5)
company_narrow

                      conm   gvkey         cik
0    A & E PLASTIK PAK INC  001000        None
1  A & M FOOD SERVICES INC  001001  0000723576
2                 AAI CORP  001002  0001306124
3    A.A. IMPORTING CO INC  001003  0000730052
4                 AAR CORP  001004  0000001750

In [11]:
apple_fund = conn.raw_sql("""select a.gvkey, a.iid, a.datadate, a.tic, a.conm,
                            a.at, b.prccm, b.cshoq 
                            
                            from comp.funda a 
                            inner join comp.secm b 
                            
                            on a.gvkey = b.gvkey
                            and a.iid = b.iid
                            and a.datadate = b.datadate 
                            
                            where a.tic = 'AAPL' 
                            and a.datadate>='01/01/1960'
                            and a.datafmt = 'STD' 
                            and a.consol = 'C' 
                            and a.indfmt = 'INDL'
                            """, date_cols=['datadate'])
print(apple_fund)
print(apple_fund.info())

     gvkey iid   datadate   tic       conm          at       prccm      cshoq
0   001690  01 1981-09-30  AAPL  APPLE INC     254.838   15.249996     55.309
1   001690  01 1982-09-30  AAPL  APPLE INC     357.787   18.249985     57.123
2   001690  01 1983-09-30  AAPL  APPLE INC     556.579   23.125000     59.198
3   001690  01 1984-09-30  AAPL  APPLE INC     788.786   25.125000     60.535
4   001690  01 1985-09-30  AAPL  APPLE INC     936.177   15.750000     61.850
5   001690  01 1986-09-30  AAPL  APPLE INC    1160.128   33.500000     62.628
6   001690  01 1987-09-30  AAPL  APPLE INC    1477.931   56.500000    126.088
7   001690  01 1988-09-30  AAPL  APPLE INC    2082.086   43.250000    122.768
8   001690  01 1989-09-30  AAPL  APPLE INC    2743.899   44.500000    126.270
9   001690  01 1990-09-30  AAPL  APPLE INC    2975.707   29.000000    115.359
10  001690  01 1991-09-30  AAPL  APPLE INC    3493.597   49.500000    118.386
11  001690  01 1992-09-30  AAPL  APPLE INC    4223.693   45.125000    118.479
12  001690  01 1993-09-30  AAPL  APPLE INC    5171.412   23.375000    116.147
13  001690  01 1994-09-30  AAPL  APPLE INC    5302.746   33.686996    119.543
14  001690  01 1995-09-30  AAPL  APPLE INC    6231.000   37.250000    122.922
15  001690  01 1996-09-30  AAPL  APPLE INC    5364.000   22.186996    124.497
16  001690  01 1997-09-30  AAPL  APPLE INC    4233.000   21.686996    127.949
17  001690  01 1998-09-30  AAPL  APPLE INC    4289.000   38.125000    135.193
18  001690  01 1999-09-30  AAPL  APPLE INC    5161.000   63.312500    160.799
19  001690  01 2000-09-30  AAPL  APPLE INC    6803.000   25.750000    335.677
20  001690  01 2001-09-30  AAPL  APPLE INC    6021.000   15.510000    350.922
21  001690  01 2002-09-30  AAPL  APPLE INC    6298.000   14.500000    358.959
22  001690  01 2003-09-30  AAPL  APPLE INC    6815.000   20.720000    366.727
23  001690  01 2004-09-30  AAPL  APPLE INC    8050.000   38.750000    391.444
24  001690  01 2005-09-30  AAPL  APPLE INC   11551.000   53.610000    835.019
25  001690  01 2006-09-30  AAPL  APPLE INC   17205.000   76.980000    855.263
26  001690  01 2007-09-30  AAPL  APPLE INC   25347.000  153.470000    872.329
27  001690  01 2008-09-30  AAPL  APPLE INC   39572.000  113.660000    888.326
28  001690  01 2009-09-30  AAPL  APPLE INC   47501.000  185.350000    899.806
29  001690  01 2010-09-30  AAPL  APPLE INC   75183.000  283.750000    915.970
30  001690  01 2011-09-30  AAPL  APPLE INC  116371.000  381.320000    929.277
31  001690  01 2012-09-30  AAPL  APPLE INC  176064.000  667.105000    939.208
32  001690  01 2013-09-30  AAPL  APPLE INC  207000.000  476.750000    899.213
33  001690  01 2014-09-30  AAPL  APPLE INC  231839.000  100.750000   5866.161
34  001690  01 2015-09-30  AAPL  APPLE INC  290479.000  110.300000   5578.753
35  001690  01 2016-09-30  AAPL  APPLE INC  321686.000  113.050000   5336.166
36  001690  01 2017-09-30  AAPL  APPLE INC  375319.000  154.120000   5126.201
37  001690  01 2018-09-30  AAPL  APPLE INC  365725.000  225.740000   4754.986
38  001690  01 2019-09-30  AAPL  APPLE INC  338516.000  223.970000   4443.236
39  001690  01 2020-09-30  AAPL  APPLE INC  323888.000  115.810000  16976.763
40  001690  01 2021-09-30  AAPL  APPLE INC  351002.000  141.500000  16426.786
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   gvkey     41 non-null     object
 1   iid       41 non-null     object
 2   datadate  41 non-null     datetime64[ns]
 3   tic       41 non-null     object
 4   conm      41 non-null     object
 5   at        41 non-null     float64
 6   prccm     41 non-null     float64
 7   cshoq     41 non-null     float64
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 2.7+ KB
None

In [12]:
data_directory = '/content/drive/My Drive/Colab Notebooks/data/'
!pwd

/content

In [13]:
apple_fund.to_pickle(data_directory + "apple_fund.pkl")

In [18]:
help(conn.describe_table)

Help on method describe_table in module wrds.sql:

describe_table(library, table) method of wrds.sql.Connection instance
    Takes the library and the table and describes all the columns
      in that table.
    Includes Column Name, Column Type, Nullable?.

    :param library: Postgres schema name.
    :param table: Postgres table name.

    :rtype: pandas.DataFrame

    Usage::
    >>> db.describe_table('wrdssec_all', 'dforms')
                name nullable     type
          0      cik     True  VARCHAR
          1    fdate     True     DATE
          2  secdate     True     DATE
          3     form     True  VARCHAR
          4   coname     True  VARCHAR
          5    fname     True  VARCHAR

In [17]:
compustat_variables=conn.describe_table('comp', 'funda')
print(compustat_variables)

Approximately 858064 rows in comp.funda.
         name  nullable              type
0       gvkey      True        VARCHAR(6)
1    datadate      True              DATE
2       fyear      True  DOUBLE_PRECISION
3      indfmt      True       VARCHAR(12)
4      consol      True        VARCHAR(2)
..        ...       ...               ...
943        au      True        VARCHAR(8)
944      auop      True        VARCHAR(8)
945    auopic      True        VARCHAR(1)
946     ceoso      True        VARCHAR(1)
947     cfoso      True        VARCHAR(1)

[948 rows x 3 columns]